In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt #matplotlib is used for plot the graphs,
%matplotlib inline
import sklearn
from sklearn import svm, preprocessing
import warnings
warnings.filterwarnings('ignore')
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import GridSearchCV

# Reading in the data

In [2]:
data=pd.read_csv('breastCancer.csv')
data=data.drop('id',axis=1)

# Cleansing and Preprocessing data

In [3]:
#Taking out the ? in the data file
from sklearn import preprocessing

for column in data.columns:
    if data[column].dtype == type(object):
        le=preprocessing.LabelEncoder()
        data[column]=le.fit_transform(data[column])

In [4]:
data #print data set
#data.shape #shape of data and number of variables

,clump_thickness,size_uniformity,shape_uniformity,marginal_adhesion,epithelial_size,bare_nucleoli,bland_chromatin,normal_nucleoli,mitoses,class
0,5,1,1,1,2,0,3,1,1,2
1,5,4,4,5,7,1,3,2,1,2
2,3,1,1,1,2,2,3,1,1,2
3,6,8,8,1,3,4,3,7,1,2
4,4,1,1,3,2,0,3,1,1,2
5,8,10,10,8,7,1,9,7,1,4
6,1,1,1,1,2,1,3,1,1,2
7,2,1,2,1,2,0,3,1,1,2
8,2,1,1,1,2,0,1,1,5,2
9,4,2,1,1,2,0,2,1,1,2
10,1,1,1,1,1,0,3,1,1,2
11,2,1,1,1,2,0,2,1,1,2
12,5,3,3,3,2,3,4,4,1,4
13,1,1,1,1,2,3,3,1,1,2
14,8,7,5,10,7,9,5,5,4,4
15,7,4,6,4,6,0,4,3,1,4
16,4,1,1,1,2,0,2,1,1,2
17,4,1,1,1,2,0,3,1,1,2
18,10,7,7,6,4,1,4,1,2,4
19,6,1,1,1,2,0,3,1,1,2
20,7,3,2,10,5,1,5,4,4,4
21,10,5,5,3,6,7,7,10,1,4
22,3,1,1,1,2,0,2,1,1,2
23,8,4,5,1,2,10,7,3,1,4
24,1,1,1,1,2,0,3,1,1,2
25,5,2,3,4,2,7,3,6,1,4
26,3,2,1,1,1,0,2,1,1,2
27,5,1,1,1,2,0,2,1,1,2
28,2,1,1,1,2,0,2,1,1,2
29,1,1,3,1,2,0,1,1,1,2
...,...,...,...,...,...,...,...,...,...,...
669,5,10,10,8,5,5,7,10,1,4
670,3,10,7,8,5,8,7,4,1,4
671,3,2,1,2,2,0,3,1,1,2
672,2,1,1,1,2,0,3,1,1,2
673,5,3,2,1,3,0,1,1,1,2
674,1,1,1,1,2,0,2,1,1,2
675,4,1,4,1,2,0,1,1,1,2
676,1,1,2,1,2,0,2,1,1,2
677,5,1,1,1,2,0,1,1,1,2
678,1,1,1,1,2,0,1,1,1,2
679,2,1,1,1,2,0,1,1,1,2
680,10,10,10,10,5,1,10,10,7,4
681,5,10,10,10,4,1,5,6,3,4
682,5,1,1,1,2,0,3,2,1,2
683,1,1,1,1,2,0,1,1,1,2
684,1,1,1,1,2,0,1,1,1,2
685,1,1,1,1,2,0,1,1,1,2
686,1,1,1,1,2,0,1,1,1,2
687,3,1,1,1,2,0,2,3,1,2
688,4,1,1,1,2,0,1,1,1,2
689,1,1,1,1,2,0,1,1,8,2
690,1,1,1,3,2,0,1,1,1,2
691,5,10,10,5,4,5,4,4,1,4
692,3,1,1,1,2,0,1,1,1,2
693,3,1,1,1,2,0,2,1,2,2
694,3,1,1,1,3,2,1,1,1,2
695,2,1,1,1,2,0,1,1,1,2
696,5,10,10,3,7,3,8,10,2,4
697,4,8,6,4,3,4,10,6,1,4
698,4,8,8,5,4,5,10,4,1,4

In [5]:
X = data.drop('class', axis=1)  # X contain features
y = data['class']               # Y contain labels

# Divide Data

Training set: A set of examples used for learning, that is to fit the parameters [i.e., weights] of the classifier.

Validation set: A set of examples used to tune the parameters [i.e., architecture, not weights] of a classifier, for example to choose the number of hidden units in a neural network.

Test set: A set of examples used only to assess the performance [generalization] of a fully specified classifier.

In [6]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.60, test_size = 0.40)
X_test, X_cv, y_test, y_cv = train_test_split(X_test, y_test, test_size = 0.50, random_state = 1)

train = pd.DataFrame(pd.concat([X_train, y_train],axis = 1))
train.to_csv("group9_train.csv")

testing = pd.DataFrame(pd.concat([X_test, y_test],axis = 1))
testing.to_csv("group9_test.csv")

cv = pd.DataFrame(pd.concat([X_cv, y_cv],axis = 1))
cv.to_csv("group9_cv.csv")

In [7]:
train.shape

(419, 10)

In [8]:
testing.head()

,clump_thickness,size_uniformity,shape_uniformity,marginal_adhesion,epithelial_size,bare_nucleoli,bland_chromatin,normal_nucleoli,mitoses,class
208,1,1,1,1,1,0,3,1,1,2
218,6,10,7,7,6,4,8,10,2,4
575,5,1,2,1,2,0,3,1,1,2
415,3,3,2,6,3,3,3,5,1,2
454,2,3,1,1,3,0,1,1,1,2

In [9]:
testing.shape

(140, 10)

In [10]:
cv.shape

(140, 10)